CREATE TABLE topicos (
  id BIGINT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(255) NOT NULL UNIQUE,
  mensaje VARCHAR(2000) NOT NULL UNIQUE,
  fecha_de_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TINYINT(1) NOT NULL DEFAULT 1,
  curso VARCHAR(50) NOT NULL,
  usuario_id BIGINT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);